#!/bin/bash
# HHG file starter 

if [[ $1 == *"start.now"* ]]
then
	~/HedgeHog/nocdc/HHG/start_HHG.py $1 $PWD
fi

if [[ $1 == *"config.ure"* ]]
then
    ~/HedgeHog/nocdc/HHG/conf_HHG.py $1
fi

if [[ $1 == *"log"* ]]
then
    ~/HedgeHog/nocdc/HHG/plot_HHG.py $1
fi
